### PR TITLE
reference, library, navigation and scroll changes

### PR DESCRIPTION
**Pull request by anshumanui**

### CODE REVIEW

**Comment by ericvergnaud** [comment]
Hi Anshuman
you need to gitignore node_modules and .DS_Store

**Comment by anshumanui** [comment]
Removed DS_Store and node_modules

**Comment by ericvergnaud** [comment]
@anshumanui I'm still seeing the .DS_Store files
please also revert your changes to  WebSite/src/resources/public/js/lib/* ?

**Comment by anshumanui** [comment]
I have kept your changes only in WebSite/src/resources/public/js/lib/*
Removed all the .DS_Store files

**Pull request merged**
